RBG v0.5.1 Bug Fixes
sdenom01/robogrow-client pull request #10
Opened 2021-01-15 17:09 UTC by sdenom01

**Story:** [When creating a TimelineEvent on an empty timeline, if you then attempt to update the timeline event, it will CREATE a new one](https://trello.com/c/5iCKj3ke/99-when-creating-a-timelineevent-on-an-empty-timeline-if-you-then-attempt-to-update-the-timeline-event-it-will-create-a-new-one)

**Story:** [“Let’s build together!” button should link to registration page](https://trello.com/c/g0MrNdCo/100-lets-build-together-button-should-link-to-registration-page)

**Story:** [GrowTimelineEdit WYSIWYG Editor is applying really weird spacing to content that has a return character in it](https://trello.com/c/C5rrVU5z/116-growtimelineedit-wysiwyg-editor-is-applying-really-weird-spacing-to-content-that-has-a-return-character-in-it)

**Description:** Aims to fix up any of the v0.5.1 bugs that have been reported, any future bug fixes that pertain to v0.5.1 should be branched from this branch.

2021-01-17 22:56 UTC, saltMonger requested changes

2021-01-17 22:56 UTC, saltMonger commented on src/GrowTimeline/GrowTimeline.jsx
> +                // var events = (foundEventIndex !== -1) ? this.state.events.splice(foundEventIndex, 1) : this.state.events;
Are these commented snippets of code necessary for future use?

2021-01-17 22:56 UTC, saltMonger commented on src/GrowTimeline/GrowTimeline.jsx
> +                window.location.reload();
We should probably think of the correct way to get these to refresh instead of just doing a window reload.

2021-01-20 15:14 UTC, sdenom01 commented on src/GrowTimeline/GrowTimeline.jsx
> +                // var events = (foundEventIndex !== -1) ? this.state.events.splice(foundEventIndex, 1) : this.state.events;
Potentially useful for non-refresh changes that we need to make...

2021-01-20 15:14 UTC, sdenom01 commented on src/GrowTimeline/GrowTimeline.jsx
> +                window.location.reload();
BLAH..... you're right.

2021-01-20 15:35 UTC, merged